# User Settings | Edit these according to your site

title: Linwei DING
email: linweiding@smail.nju.edu.cn
author: Linwei DING

description: > Graduate Student, School of Arts, Nanjing University. Email: linweiding@smail.nju.edu.cn
  Welcome to my home page! My name is Linwei Ding. I am a graduate student in the School of Arts, Nanjing University. I Graduated from Xiamen University in 2022 with double degrees in art and management, major in musicology and accounting.

Research Interests
My research interests focus on art communication and media culture, musicology and sound cultural study, and digital platform culture. As a mixed method researcher, I use qualitative methods such as ethnography into the society’s culture phenomenon, along with data analysis methods.

Personal Skills
I own plentiful experience in art institution operation and event planning. Meanwhile, I have both statistical software data analysis capabilities and professional skills in financial management and accounting.

url: 
baseurl: 
twitter_username: ding_linwei


permalink:          /:year/:title.html

paginate: 4
paginate_path: "/page/:num"
comments: true

heading_font: Lobster 
about_footer: true
short_bio: >
   
profile_picture: http://img3.rnkr-static.com/list_img/11570/111570/C300/movies-and-films-directed-by-charlie-chaplin-u4.jpg

google_analytics: true
tracking_id: UA-69243698-5

# Build settings | Do not edit anything below this
markdown: kramdown

gems:
  - jekyll-paginate

sass:
  style:            compressed
  sass_dir:         _sass

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
